services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=mediumApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
  server:
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev
    container_name: server
    restart: always
    tty: true
    environment:
      - DATABASE_URL="postgresql://postgres:password@db/app?connect_timeout=600"
      - PORT=8080
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes: # if there's any new files containing sources, add them as volumes
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
volumes:
  db-data:


# version: '3'
# services:
#   database:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=medium
#     ports:
#       - '5432:5432'
#     volumes:
#       - database:/var/lib/postgresql/data
# volumes:
#   database:
#     driver: local